In [3]:
import pandas as pd
import os

print("Files in directory:", os.listdir())

Files in directory: ['NIFTY50_Zret_Sorted.xlsx', 'assignment_VOL_data.xlsx', 'NIFTY50_Zret_Compare.xlsx', '.DS_Store', '~$NIFTY500_Zvol.xlsx', 'assignment-1.ipynb', 'requirements.txt', 'NIFTY50_Historical_PR_01021990to27022025 copy.csv', 'NIFTY50_Historical_PR_01021990to27022025.csv', 'assignment-2.ipynb', 'S&P 500 Historical Data-2.csv', 'SNP500_Vol_Graph.ipynb', 'README.md', 'NIFTY500_Zvol.xlsx', 'Nifty500_Vol_Graph.ipynb', 'Nifty50_Vol.py', 'SNP500.xlsx', 'NIFTY 500_Historical_PR_01011990to25032025.csv', '.gitignore', '~$SNP500_Zvol.xlsx', 'NIFTY50.csv', 'venv', 'SNP500_Zvol.xlsx', '.git', 'Nifty50_Vol.ipynb', 'NIFTY 50_Historical_PR_01011990to25032025.csv', 'assignment2exp.py']

In [ ]:
df=pd.read_csv('NIFTY 50_Historical_PR_01011990to25032025.csv')
#df=pd.read_excel('assignment_VOL_data.xlsx')

In [4]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,Date,Close,Log_Return,daily % chg,20day vol,previous 20d return,next 20 day return,zvol20,zfret20,zret20
0,1960-01-04,59.910000,NaN,NaN,NaN,NaN,-0.065932,NaN,NaN,NaN
1,1960-01-05,60.389999,0.007980,0.008012,NaN,NaN,-0.059116,NaN,NaN,NaN
2,1960-01-06,60.130001,-0.004315,-0.004305,NaN,NaN,-0.063363,NaN,NaN,NaN
3,1960-01-07,59.689999,-0.007344,-0.007318,NaN,NaN,-0.057296,NaN,NaN,NaN
4,1960-01-08,59.500000,-0.003188,-0.003183,NaN,NaN,-0.059160,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
10318,2000-12-22,1305.949951,0.024094,0.024387,0.016417,-0.026696,NaN,0.833996,-0.508096,NaN
10319,2000-12-26,1315.189941,0.007050,0.007075,0.017058,-0.025041,NaN,0.991458,-0.465126,NaN
10320,2000-12-27,1328.920044,0.010386,0.010440,0.017097,-0.005366,NaN,0.994110,-0.016248,NaN
10321,2000-12-28,1334.219971,0.003980,0.003988,0.017163,-0.005746,NaN,1.003813,-0.020505,NaN
10322,2000-12-29,1320.280029,-0.010503,-0.010448,0.017158,0.004053,NaN,0.995240,0.202826,NaN

In [5]:
df['Daily_returns']=df["Close"].pct_change()
df

,Date,Close,Log_Return,daily % chg,20day vol,previous 20d return,next 20 day return,zvol20,zfret20,zret20,Daily_returns
0,1960-01-04,59.910000,NaN,NaN,NaN,NaN,-0.065932,NaN,NaN,NaN,NaN
1,1960-01-05,60.389999,0.007980,0.008012,NaN,NaN,-0.059116,NaN,NaN,NaN,0.008012
2,1960-01-06,60.130001,-0.004315,-0.004305,NaN,NaN,-0.063363,NaN,NaN,NaN,-0.004305
3,1960-01-07,59.689999,-0.007344,-0.007318,NaN,NaN,-0.057296,NaN,NaN,NaN,-0.007318
4,1960-01-08,59.500000,-0.003188,-0.003183,NaN,NaN,-0.059160,NaN,NaN,NaN,-0.003183
...,...,...,...,...,...,...,...,...,...,...,...
10318,2000-12-22,1305.949951,0.024094,0.024387,0.016417,-0.026696,NaN,0.833996,-0.508096,NaN,0.024387
10319,2000-12-26,1315.189941,0.007050,0.007075,0.017058,-0.025041,NaN,0.991458,-0.465126,NaN,0.007075
10320,2000-12-27,1328.920044,0.010386,0.010440,0.017097,-0.005366,NaN,0.994110,-0.016248,NaN,0.010440
10321,2000-12-28,1334.219971,0.003980,0.003988,0.017163,-0.005746,NaN,1.003813,-0.020505,NaN,0.003988
10322,2000-12-29,1320.280029,-0.010503,-0.010448,0.017158,0.004053,NaN,0.995240,0.202826,NaN,-0.010448

In [7]:
df['20-day_Volatility'] = df['Daily_returns'].rolling(window=20).std()

print(df.iloc[15:26])

         Date      Close  Log_Return  daily % chg  20day vol  \
15 1960-01-25  56.779999   -0.010512    -0.010457        NaN
16 1960-01-26  56.860001    0.001408     0.001409        NaN
17 1960-01-27  56.720001   -0.002465    -0.002462        NaN
18 1960-01-28  56.130001   -0.010456    -0.010402        NaN
19 1960-01-29  55.610001   -0.009307    -0.009264        NaN
20 1960-02-01  55.959999    0.006274     0.006294   0.005926
21 1960-02-02  56.820000    0.015251     0.015368   0.006202
22 1960-02-03  56.320000   -0.008839    -0.008800   0.007070
23 1960-02-04  56.270000   -0.000888    -0.000888   0.007184
24 1960-02-05  55.980000   -0.005167    -0.005154   0.007136
25 1960-02-08  55.320000   -0.011860    -0.011790   0.007153

    previous 20d return  next 20 day return  zvol20  zfret20  zret20  \
15                  NaN           -0.014794     NaN      NaN     NaN
16                  NaN           -0.019697     NaN      NaN     NaN
17                  NaN           -0.013928     NaN      NaN     NaN
18                  NaN            0.000534     NaN      NaN     NaN
19                  NaN            0.009171     NaN      NaN     NaN
20            -0.065932            0.000893     NaN      NaN     NaN
21            -0.059116           -0.021119     NaN      NaN     NaN
22            -0.063363           -0.027344     NaN      NaN     NaN
23            -0.057296           -0.030211     NaN      NaN     NaN
24            -0.059160           -0.035013     NaN      NaN     NaN
25            -0.058703           -0.033442     NaN      NaN     NaN

    Daily_returns  20-day_Volatility
15      -0.010457                NaN
16       0.001409                NaN
17      -0.002462                NaN
18      -0.010402                NaN
19      -0.009264                NaN
20       0.006294           0.006202
21       0.015368           0.007070
22      -0.008800           0.007184
23      -0.000888           0.007136
24      -0.005154           0.007153
25      -0.011790           0.007121

In [11]:
df["250_Mean"] = df["20-day_Volatility"].rolling(window=250).mean()
df["250_SD"] = df["20-day_Volatility"].rolling(window=250).std(ddof=0)  # Population SD

# Compute Zret20Vol using `250_Mean` instead of `.mean()` (to match Excel)
df["Z20Vol"] = (df["20-day_Volatility"] - df["250_Mean"].shift(1)) / df["250_SD"].shift(1)
output_file = "NIFTY50_Zret_Compare.xlsx"
df.to_excel(output_file, sheet_name="Compare_Zret", index=False)
df[260:280]

,Date,Close,Log_Return,daily % chg,20day vol,previous 20d return,next 20 day return,zvol20,zfret20,zret20,Daily_returns,20-day_Volatility,250_Mean,250_SD,Zret20Vol,Z20Vol
260,1961-01-13,59.599998,0.004709,0.004720,0.005100,0.048557,0.031879,NaN,NaN,NaN,0.004720,0.005086,NaN,NaN,NaN,NaN
261,1961-01-16,59.580002,-0.000336,-0.000336,0.005086,0.051164,0.026183,NaN,NaN,NaN,-0.000336,0.004982,NaN,NaN,NaN,NaN
262,1961-01-17,59.639999,0.001006,0.001007,0.004982,0.042657,0.029678,NaN,NaN,NaN,0.001007,0.004735,NaN,NaN,NaN,NaN
263,1961-01-18,59.680000,0.000670,0.000671,0.004735,0.044635,0.037533,NaN,NaN,NaN,0.000671,0.004684,NaN,NaN,NaN,NaN
264,1961-01-19,59.770000,0.001507,0.001508,0.004684,0.046943,0.042329,NaN,NaN,NaN,0.001508,0.004638,NaN,NaN,NaN,NaN
265,1961-01-20,59.959999,0.003174,0.003179,0.004638,0.041877,0.035690,NaN,NaN,NaN,0.003179,0.004444,NaN,NaN,NaN,NaN
266,1961-01-23,60.290001,0.005489,0.005504,0.004444,0.050531,0.033671,NaN,NaN,NaN,0.005504,0.004354,NaN,NaN,NaN,NaN
267,1961-01-24,60.450001,0.002650,0.002654,0.004354,0.052403,0.031596,NaN,NaN,NaN,0.002654,0.004337,NaN,NaN,NaN,NaN
268,1961-01-25,60.529999,0.001322,0.001323,0.004337,0.052330,0.034033,NaN,NaN,NaN,0.001323,0.004338,NaN,NaN,NaN,NaN
269,1961-01-26,60.619999,0.001486,0.001487,0.004338,0.049152,0.036622,NaN,NaN,NaN,0.001487,0.004319,0.006251,0.001578,NaN,NaN
270,1961-01-27,61.240002,0.010176,0.010228,0.004319,0.054953,0.033638,-1.229365,1.513737,0.721850,0.010228,0.004639,0.006245,0.001581,-1.021466,-1.021466
271,1961-01-30,61.970001,0.011850,0.011920,0.004639,0.066426,0.023721,-1.019421,1.835700,0.426471,0.011920,0.005055,0.006237,0.001582,-0.752543,-0.752543
272,1961-01-31,61.779999,-0.003071,-0.003066,0.005055,0.073128,0.026708,-0.751036,2.014070,0.509438,-0.003066,0.004391,0.006226,0.001585,-1.166621,-1.166621
273,1961-02-01,61.900002,0.001941,0.001942,0.004391,0.060658,0.031502,-1.164286,1.637665,0.645076,0.001942,0.003688,0.006212,0.001592,-1.600961,-1.600961
274,1961-02-02,62.299999,0.006441,0.006462,0.003688,0.063684,0.026485,-1.597756,1.712923,0.491147,0.006462,0.003769,0.006198,0.001599,-1.534393,-1.534393
275,1961-02-03,62.220001,-0.001285,-0.001284,0.003769,0.065411,0.029412,-1.531321,1.750213,0.571925,-0.001284,0.003648,0.006184,0.001606,-1.595035,-1.595035
276,1961-02-06,61.759998,-0.007421,-0.007393,0.003648,0.050161,0.027688,-1.591842,1.296387,0.514907,-0.007393,0.004227,0.006171,0.001608,-1.218864,-1.218864
277,1961-02-07,61.650002,-0.001783,-0.001781,0.004227,0.045447,0.029035,-1.216424,1.150123,0.549215,-0.001781,0.004331,0.006158,0.001609,-1.144184,-1.144184
278,1961-02-08,62.209999,0.009042,0.009083,0.004331,0.051911,0.020736,-1.141894,1.328844,0.296190,0.009083,0.004594,0.006147,0.001611,-0.971591,-0.971591
279,1961-02-09,62.020000,-0.003059,-0.003054,0.004594,0.045516,0.023541,-0.969646,1.134403,0.375714,-0.003054,0.004759,0.006135,0.001610,-0.861841,-0.861841

In [102]:
df_filtered = df.dropna(subset=["Zret20Vol"])
df_sorted = df_filtered.sort_values(by="Zret20Vol", ascending=False)
df_sorted.head(-20)
output_file = "NIFTY50_Zret_Sorted.xlsx"
df_sorted.to_excel(output_file, sheet_name="Sorted_Zret", index=False)